{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 10, "max_value": 30, "step": 5, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "sigmoid", "tanh", "elu"], "ordered": false}}, {"class_name": "Float", "config": {"name": "dropout", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.2, "step": 0.05, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "lr", "default": 1e-06, "conditions": [], "min_value": 1e-06, "max_value": 0.1, "step": null, "sampling": "log"}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "RMSprop", "SGD"], "ordered": false}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 10, "max_value": 30, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 10, "max_value": 30, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 10, "max_value": 30, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_4", "default": null, "conditions": [], "min_value": 10, "max_value": 30, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_5", "default": null, "conditions": [], "min_value": 10, "max_value": 30, "step": 5, "sampling": "linear"}}], "values": {"num_layers": 6, "units_0": 25, "activation": "elu", "dropout": 0.0, "lr": 0.008250093557073582, "optimizer": "SGD", "units_1": 10, "units_2": 10, "units_3": 10, "units_4": 10, "units_5": 10}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/runpy.py\", line 198, in _run_module_as_main\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/runpy.py\", line 88, in _run_code\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/asyncio/base_events.py\", line 608, in run_forever\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/asyncio/base_events.py\", line 1936, in _run_once\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/asyncio/events.py\", line 84, in _run\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/var/folders/6w/vv6mxd6s5tn2fg5xf8lytbl40000gp/T/ipykernel_64618/3651685660.py\", line 2, in <module>\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/opt/homebrew/Caskroom/miniconda/base/envs/xgboost_env/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\ncould not find registered platform with id: 0x1665a65b0\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_multi_step_on_iterator_6790]\n"}